name = "shotten-app"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://bvwjoptvnxpttwkstiue.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_YaWg2zCaLJqZrVYv0K-9sQ_vXXYEImm"

# For API routes that need write access (use Cloudflare dashboard to set this as a secret)
# SUPABASE_SERVICE_KEY = "sb_secret_..."
